[package]
name = "amdgpu-fancontrol"
version = "0.1.0"
authors = ["Mike Cronce <mike@quadra-tec.net>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = "thin"
debug = false

[dependencies]
envconfig = "^0.7"
envconfig_derive = "^0.7"
glob = "^0.3"

